# Generated by Django 2.0.5 on 2018-05-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_inqueue',
            field=models.BooleanField(default=True),
        ),
    ]
